server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true  

logging.level.org.springframework: INFO
logging.level.com.sb.test.examples: INFO    
# Log Thresolds
logging.threshold.console: INFO
logging.threshold.file: INFO

# Log to File
logging.file: c://temp//app.log

# Log Patterns
logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%'